### ISSUE TITLE
how to run it on my own dataset?

### ISSUE THREAD

**Issue by PanPan0210** [wulalago/UNet#2]
when i run this main.py on my own dataset , i found it doesn't work.`Epoch 002 || Loss: 0.6832 | Time: 4.32 | Test Dice: 0.0000 
Epoch 003 || Loss: 0.6596 | Time: 4.40 | Test Dice: 0.0000 
Epoch 004 || Loss: 0.6414 | Time: 4.43 | Test Dice: 0.0000 
Epoch 005 || Loss: 0.6292 | Time: 4.26 | Test Dice: 0.0759 
Epoch 006 || Loss: 0.6199 | Time: 4.28 | Test Dice: 0.0412 
Epoch 007 || Loss: 0.6121 | Time: 4.31 | Test Dice: 0.0338 
Epoch 008 || Loss: 0.6057 | Time: 4.64 | Test Dice: 0.0474 
Epoch 009 || Loss: 0.6000 | Time: 4.69 | Test Dice: 0.0550 
Epoch 010 || Loss: 0.5956 | Time: 4.65 | Test Dice: 0.0593 
Epoch 011 || Loss: 0.5915 | Time: 4.68 | Test Dice: 0.2090 
Epoch 012 || Loss: 0.5881 | Time: 4.45 | Test Dice: 0.2034 
Epoch 013 || Loss: 0.5848 | Time: 4.62 | Test Dice: 0.2277 
Epoch 014 || Loss: 0.5817 | Time: 4.95 | Test Dice: 0.2125 
Epoch 015 || Loss: 0.5787 | Time: 4.53 | Test Dice: 0.2732 
Epoch 016 || Loss: 0.5763 | Time: 4.63 | Test Dice: 0.3080 
Epoch 017 || Loss: 0.5746 | Time: 4.25 | Test Dice: 0.4159 
Epoch 018 || Loss: 0.5728 | Time: 4.24 | Test Dice: 0.3419 
Epoch 019 || Loss: 0.5700 | Time: 4.31 | Test Dice: 0.4312 
Epoch 020 || Loss: 0.5678 | Time: 4.73 | Test Dice: 0.4860 `

how can i solve it ?

**Comment by wulalago** [comment]
I found that your training time is only 4 seconds per epoch. What is the size of your datset? I don't know the difficulty of your task, You can increase the number of training epochs and use the data augmentation, (for example, rotation, scale, flip...), which may improve your performance and make your training more stable. I hope this will help you.

**Comment by 15793723081** [comment]
Hello, have you run through your data set with this code?May I have your contact information?Let's communicate, thank you!

**Comment by wulalago** [comment]
> Hello, have you run through your data set with this code?May I have your contact information?Let's communicate, thank you!

I have added your QQ,  please agree. Thanks.
