### ISSUE TITLE
找不到Log文件

### ISSUE THREAD

**Issue by 15793723081** [wulalago/UNet#4]
![image](https://user-images.githubusercontent.com/48192727/65408994-3bc7a880-de19-11e9-91d4-ef4e21161fa3.png)

After running the code on the server, I can't find the generated log file. The log folder is empty，as shown above.And I want to know how many samples do you have in your data set?Did you visualize the images before and after training?

**Comment by wulalago** [comment]
You can change the line-98 in main.py to: open(os.path.join(log_path, 'train_log.txt'), 'a+').write(info_line+'\n'). The mode of oepn function should be 'a+', not 'a', I have already fixed the bug.

I used 20 3D Ultrasound Volume as the dataset.
